stages:
  get_data:
    cmd: python src/support/get_data.py
    deps:
    - src/support/get_data.py
    outs:
    - data/
  process-train:
    cmd: python src/model/training_model.py
    deps:
    - src/model/training_model.py
    - src/support/evaluation.py
    - data/
    - h5_files/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224.h5
    outs:
    - h5_files/final_model.h5
    - src/suppot/model_evolution.png
    metrics:
      - src/support/metrics.json:
          cache: false

