name: anomaly-detector-flow-1
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          dvc pull
          dvc repro

          # Write your CML report
          git fetch --prune
          dvc push .
          dvc metrics diff --show-md main > report.md

          # add figures to the report
          echo "## Modle training results"
          cml-publish model_evolution.png --md >> report.md
          cml-send-commit report.md
